#!/sbin/sh

# Galaxy S3 mini block device
SYSTEMDEV="/dev/block/mmcblk0p22"
DATADEV="/dev/block/mmcblk0p25"
CACHEDEV="/dev/block/mmcblk0p23"

echo $0 $* >> /dev/null

if echo "$*" | grep -q -i "remount"; then
    REMOUNT=",remount";
else
    REMOUNT="";
fi;

if (echo "$*" | grep -q -i "/system"); then
    busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=1$REMOUNT $SYSTEMDEV /system >> /dev/null 2>&1
    echo busybox mount -o rw$REMOUNT $SYSTEMDEV /system >> /dev/null
elif (echo "$*" | grep -q -i "/cache"); then
    busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=1$REMOUNT $CACHEDEV /cache >> /dev/null 2>&1
    echo busybox mount -o rw$REMOUNT $CACHEDEV /cache >> /dev/null
elif (echo "$*" | grep -q -i "/data"); then
    busybox mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=1$REMOUNT $DATADEV /data >> /dev/null 2>&1
    echo busybox mount -o rw$REMOUNT $DATADEV /data >> /dev/null
else
    busybox mount $*
    echo busybox mount $* >> /dev/null
fi;
